function T = RobotModelFK_Kuka(q,params,sigma,Tbase,Ttool)
d_1=.350;  %link 1 length-203.2
d_2=1.150; %link 2 length
d_3=1.200; %link 3 length (between in j3 and SW)
d_4=-.041;  %shift in z between j3 and j4 
d5 = 0.215;  %link 5 length (between in SW and ee)
% T = Tbase*R_T(Rz(pi/2))*...
%     R_T(Rz(q(1)))*Ty(params(1))*Tx(params(2))*R_T(Rx(params(3)))* ...
%     R_T(Ry(q(2)+params(4)))*Tx(params(5))*R_T(Rx(params(6)))*R_T(Rz(params(7)))* ...
%     R_T(Ry(q(3)+params(8)))*Tx(params(9))*Tz(params(10))*R_T(Rz(params(11)))* ...
%     R_T(Rx(q(4)+params(12)))*Ty(params(13))*Tz(params(14))*R_T(Rz(params(15)))* ...
%     R_T(Ry(q(5)+params(16)))*Tz(params(17))*R_T(Rz(params(18)))*...
%     R_T(Rx(q(6)))*Tx(d5)*...
%     Ttool;

% T = Tbase*...
%     R_T(Rz(q(1)))*Tx(params(1))*Ty(params(2))*R_T(Ry(params(3)))* ...
%     R_T(Rx(q(2)+params(4)))*Ty(params(5))*R_T(Ry(params(6)))*R_T(Rz(params(7)))* ...
%     R_T(Rx(q(3)+params(8)))*Ty(params(9))*Tz(params(10))*R_T(Rz(params(11)))* ...
%     R_T(Ry(q(4)+params(12)))*Tx(params(13))*Tz(params(14))*R_T(Rz(params(15)))* ...
%     R_T(Rx(q(5)+params(16)))*Tz(params(17))*R_T(Rz(params(18)))*...
%     R_T(Ry(q(6)))*Ty(d5)*...
%     Ttool;

T = Tbase*...
    R_T(Rz(q(1)))*Ty(d_1)/...
    R_T(Rx(q(2)+params(1)))*Ty(d_2)*...
    R_T(Rx(q(3)+params(2)))*Ty(d_3)*Tz(d_4)*...
    R_T(Ry(q(4)+params(3)))* ...
    R_T(Rx(q(5)+params(4)))*...
    R_T(Ry(q(6)))*Ty(d5)*...
    Ttool;
T(1,4) = -T(1,4);
end
